name: License Headers

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-license-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check license headers
        run: bash scripts/check_license_headers.sh
